server:
  port: "2222"
  ssh_key_path: ".ssh_host_rsa_key"

python_vfs:
  address: "vfs:5000"
  auth_token: "HoneypotSuperSecretToken123!"

telemetry:
  clickhouse_url: "clickhouse:9000"
  password: "123456"

ai_fallback:
  api_key: "AQ.Ab8RN6L7t3vIvSl059Cpo7unMStR3748qWfD3JOx43X149Oh2Q"