server:
  ssh_key_path: ".ssh_host_rsa_key"

telemetry:
  clickhouse_url: "clickhouse:9000"
  password: "YOUR_CLICKHOUSE_PASS"

python_vfs:
  address: "vfs:5000"
  auth_token: "secret-token-123"

ai_fallback:
  api_key: "YOUR_GEMINI_API_KEY_HERE"