FROM python:3.11-slim
WORKDIR /app
COPY internal/environments/fake /app/internal/environments/fake
RUN apt-get update && apt-get install -y openssh-server net-tools iproute2 curl iputils-ping
ENV PYTHONPATH=/app
EXPOSE 5000
CMD ["python", "internal/environments/fake/server.py"]
