services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: honeypot-clickhouse
    ports:
    - "8123:8123" # HTTP Port
    - "9000:9000" # Native Port 
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  vfs:
    build:
      context: .
      dockerfile: Dockerfile.vfs
    container_name: honeypot_vfs
    ports:
      - "5000:5000"
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    container_name: honeypot_gateway
    ports:
      - "2222:2222"
    volumes:
      - ./config.yaml:/app/config.yaml
      # Go kodunun Docker konteynerleri yaratabilmesi için Docker Socket'i bağlıyoruz:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - clickhouse
      - vfs
    restart: unless-stopped

volumes:
  clickhouse_data: