version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: honeypot-clickhouse
    ports:
    - "8123:8123" # HTTP Port
    - "9000:9000" # Native Port 
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=123456
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  clickhouse_data: