// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/health": {
            "get": {
                "description": "Checks if the Gateway and Database are running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Check System Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/logs/ebpf": {
            "get": {
                "description": "Retrieves the latest eBPF logs captured by the honeypot",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Get eBPF Kernel Logs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of logs to retrieve",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/telemetry.EBPFLog"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/logs/http": {
            "get": {
                "description": "Retrieves the latest HTTP logs captured by the honeypot",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Get HTTP Logs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of logs to retrieve",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/telemetry.HTTPLog"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/logs/ssh": {
            "get": {
                "description": "Retrieves the latest eBPF logs captured by the honeypot",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "logs"
                ],
                "summary": "Get SSH Command Logs",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of logs to retrieve",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/telemetry.CommandLog"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "telemetry.CommandLog": {
            "type": "object",
            "properties": {
                "command": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "output": {
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "telemetry.EBPFLog": {
            "type": "object",
            "properties": {
                "log": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "telemetry.HTTPLog": {
            "type": "object",
            "properties": {
                "ip_address": {
                    "type": "string"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "payload": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "user_agent": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
